on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-jdk8-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-jdk8
            
      - name: Create Artifacts
        run: |
          ./gradlew uberJar
      
      - name: Delete Previous master-branch-latest Tag
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          delete_release: true
          tag_name: master-branch-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create_release 
        # note id is referenced below in Deploy uberJar
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: master-branch-latest
          prerelease: true
                
      - name: Deploy UberJar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          # This pulls from the CREATE RELEASE step above, referencing its ID to get its outputs object, which include a `upload_url` 
          asset_path: build/libs/synthea-with-dependencies.jar
          asset_name: synthea-with-dependencies.jar
          asset_content_type: application/java-archive
        
        # it's necessary to add another "publish" at the end because otherwise the release is always listed as "draft"
        # see https://github.com/actions/upload-release-asset/issues/34
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          replacesArtifacts: false
          tag: master-branch-latest
          token: ${{ secrets.GITHUB_TOKEN }}
